export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INACTIVE_ADMIN: 'AUTH_INACTIVE_ADMIN',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_NOT_ACTIVE: 'MEMBER_NOT_ACTIVE',
  TRAINER_NOT_FOUND: 'TRAINER_NOT_FOUND',
  TRAINER_INACTIVE: 'TRAINER_INACTIVE',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  PACKAGE_INACTIVE: 'PACKAGE_INACTIVE',
  PACKAGE_RULE_INVALID: 'PACKAGE_RULE_INVALID',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_NOT_ACTIVE: 'CARD_NOT_ACTIVE',
  CARD_EXPIRED: 'CARD_EXPIRED',
  CARD_VISITS_NOT_ENOUGH: 'CARD_VISITS_NOT_ENOUGH',
  CARD_LESSONS_NOT_ENOUGH: 'CARD_LESSONS_NOT_ENOUGH',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_TIME_INVALID: 'APPOINTMENT_TIME_INVALID',
  APPOINTMENT_CONFLICT_TRAINER: 'APPOINTMENT_CONFLICT_TRAINER',
  APPOINTMENT_CONFLICT_MEMBER: 'APPOINTMENT_CONFLICT_MEMBER',
  APPOINTMENT_STATUS_INVALID: 'APPOINTMENT_STATUS_INVALID',
  ACCESS_DENIED: 'ACCESS_DENIED',
  PRESENCE_NOT_IN_GYM: 'PRESENCE_NOT_IN_GYM'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
